***SciPy offers complex algorithms and their use as functions in Numpy.
This allocates high-level commands and a variety of classes to manipulate and
visualize data.
SciPy is curated in the form of multiple small packages,with each package 
targeting individual scientific computing domains.
A few of the subpackages are linalg(linear algebra), constants(Physical and mathematical constants)
and sparse(sparse matrics and associated routines)
Most of NumPy package functions applicable on arrays are also included in SciPy package.
SciPy offers pre-tested routines,thereby saving a lot of time in the scientific
computing applications.***

In [1]:
import scipy
import numpy as np

In [2]:
from scipy import linalg

In [3]:
m =np.array([[2,3,1],[4,5,6],[10,3,5]]) #matrix creation
print(m)

[[ 2  3  1]
 [ 4  5  6]
 [10  3  5]]


In [5]:
linalg.det(m) #Determinant of matrix

96.0

In [6]:
in_m = linalg.inv(m)
print(in_m)

[[ 7.29166667e-02 -1.25000000e-01  1.35416667e-01]
 [ 4.16666667e-01 -1.16865582e-17 -8.33333333e-02]
 [-3.95833333e-01  2.50000000e-01 -2.08333333e-02]]


In [7]:
#Singular value decomposition
comp1,comp2,comp3 = linalg.svd(m)
print(comp1)
print(comp2)
print(comp3)

[[-0.22658249 -0.25496637 -0.94002794]
 [-0.5723741  -0.74603899  0.34031415]
 [-0.78806616  0.61515687  0.02310323]]
[14.33566388  4.10159803  1.6326772 ]
[[-0.74104158 -0.41196672 -0.53022713]
 [ 0.64791331 -0.64599784 -0.40360268]
 [-0.1762547  -0.64262758  0.74562998]]


In [ ]:
#Generating a random sample of size 20 from normal distribution with mean3 and SD5

In [8]:
from scipy import stats
rvs_20 = stats.norm.rvs(3,5,size=20)
print(rvs_20)

[ 3.68012844 -2.11578097 -0.14833899  8.97321642  3.61325538  0.78280377
  4.79947756  9.26687407 -0.84730419  0.26303696  1.20699865 -2.8803705
  4.70273674  8.96659278 -1.77273477  2.93380483  1.78988867  5.17118594
  0.16701477  2.60397292]


In [9]:
#Computing CDF of Beta distribution with a=100,b=130 as shape parameters at randomvarible 0.41

In [10]:
cdf_=scipy.stats.beta.cdf(0.41,a=100,b=130)
print(cdf_)

0.22500957436155394
