***Numpy is used particularly for scientific computing in Python.It is designed to efficiently manipulate
large multidimensional arrays of arbitary records, without sacrificing too much speed for small 
multidimensional arrays.***





In [4]:
import numpy as np
a=np.array([1,4,5,8],float)
print(type(a))

<class 'numpy.ndarray'>


In [7]:
a[0]=5   #replacing
print(a)

[5. 4. 5. 8.]


In [9]:
b=np.array([[1,2,3],[4,5,6]],float) #2D array
b[0,1]

2.0

In [12]:
print(b.shape)  #Retuens tuple with shape of array

(2, 3)


In [13]:
b.dtype #Returns type of value stored

dtype('float64')

In [14]:
type(b)  #Type of variable

numpy.ndarray

In [15]:
print(len(b))  # returns length of b

2


In [16]:
2 in b

True

In [17]:
0 in b

False

In [18]:
c=np.array(range(12),float)
print(c)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]


In [19]:
print(c.shape)

(12,)


In [20]:
c.fill(0)

In [21]:
print(c)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [22]:
c.transpose()

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [23]:
c=c.reshape(2,6)

In [24]:
print(c)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [25]:
c.flatten()

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [27]:
m=np.array([1,2],float)
n=np.array([3,4,5],float)
p=np.concatenate((m,n))   #concatenate  2 or more arrays
print(p)

[1. 2. 3. 4. 5.]


In [28]:
print(p.shape)

(5,)


In [30]:
#new axis to increase dimensionality
q=np.array([1,3,4],float)
q[:,np.newaxis].shape

(3, 1)

In [32]:
q.shape

(3,)

In [33]:
a1=np.array([[1,2],[3,4],[5,6]],float)
a2=np.array([-1,3],float)
print(a1+a2)

[[0. 5.]
 [2. 7.]
 [4. 9.]]


In [34]:
a3=np.array([[0,2],[3,-1],[3,5]],float)
print(a3.mean(axis=0))  #Mean of elements columnwise

[2. 2.]


In [36]:
print(a3.mean(axis=1))  #Mean of elements rowwise

[1. 1. 4.]


In [45]:
a4=np.array([1,3,0],float)
np.where(a!=0,1/a,a)

array([0.2  , 0.25 , 0.2  , 0.125])

In [46]:
np.random.rand(2,3)

array([[0.14945886, 0.38790947, 0.69016162],
       [0.00588902, 0.77418605, 0.67605911]])